# Generated by Django 4.2 on 2025-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('field_of_work', models.CharField(max_length=100, verbose_name='زمینه فعالیت')),
                ('medical_system_code', models.CharField(max_length=20, unique=True, verbose_name='کد نظام پزشکی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('city', models.CharField(choices=[('tehran', 'تهران'), ('mashhad', 'مشهد'), ('isfahan', 'اصفهان'), ('shiraz', 'شیراز'), ('tabriz', 'تبریز'), ('ahvaz', 'اهواز'), ('karaj', 'کرج'), ('qom', 'قم'), ('kermanshah', 'کرمانشاه'), ('rasht', 'رشت'), ('urmia', 'ارومیه'), ('zahedan', 'زاهدان'), ('sanandaj', 'سنندج'), ('gorgan', 'گرگان'), ('ardabil', 'اردبیل')], max_length=20, verbose_name='شهر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
