# Generated by Django 4.2 on 2025-07-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dentist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ روز کاری')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='dentist_app.dentistmodel')),
            ],
            options={
                'unique_together': {('dentist', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='ساعت نوبت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات بیمار')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dentist_app.workday')),
            ],
            options={
                'unique_together': {('work_day', 'time')},
            },
        ),
    ]
