# Generated by Django 4.2 on 2025-06-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_customuser_insurance_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, choices=[('khorramabad', 'خرم\u200cآباد'), ('borujerd', 'بروجرد'), ('dorud', 'دورود'), ('kuhdasht', 'کوهدشت'), ('alishtar', 'الشتر'), ('noodshahr', 'نورآباد'), ('azna', 'ازنا'), ('aligdarzeh', 'الیگودرز'), ('sepiddasht', 'سپیددشت'), ('poldokhtar', 'پلدختر')], max_length=20, verbose_name='شهر'),
        ),
    ]
