# Generated by Django 4.2 on 2025-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='history_of_illness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تاریخچه بیماری'),
        ),
    ]
